[project]
name = "task-management-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=4.1.0",
    "langchain>=1.4.4",
    "langchain-core>=1.6.9",
    "langchain-groq>=1.1.3",
    "psycopg>=3.3.6",
    "pycopg[binary]>=1.2.0",
    "python-dotenv>=1.2.4",
]

[project.scripts]
task-management-agent = "task_management_agent:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
